# Site settings
title: Álvaro García Delgado
email: alvaro.garcia.de@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The purpose of this site is collecting some Scala knowledge that may be useful to me in case I need to remember
  quickly or even to anyone who needs to go deeper in any of the topics I write about. Any suggestions are welcome.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://algd.github.io" # the base hostname & protocol for your
host: 0.0.0.0
twitter_username:
github_username:  algd
linkedin_username: alvaro-garcia-delgado
linkedin_name: Álvaro García

# Build settings
markdown: kramdown

theme: jekyll-theme-leap-day